### PR TITLE
PHP8.2 ready

### PR DESCRIPTION
**Pull request by schengawegga**
Some changes to become PHP8.2 ready

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
I'm not sure about this.
Pear DB did its thing.
Pear MDB2 came along, and it was an improvement.
PHP then brought in PHP's PDO approach, and that was (another) improvement.

What PEAR specific packages are relying on this, and more importantly, should they be?

**Comment by schengawegga** [comment]
> I'm not sure about this.
> Pear DB did its thing.
> Pear MDB2 came along, and it was an improvement.
> PHP then brought in PHP's PDO approach, and that was (another) improvement.
> 
> What PEAR specific packages are relying on this, and more importantly, should they be?
> 

But there are users out there wich are using still pear/db in their projects. And changing the database abstraction class to MDB or PDO takes a lot of time and work, depending on how big the project is. So we should keep this package alive for all these long living projects.

And pear/auth, pear/log or pear/mail_queue uses this package optional for database transactions, for example.

So my goal is, to keep as many pear packages alive, as my time allows. Because I use several of this packages in my projects, too. And I know how frustrating it can be, if a deep implemented package was abandoned. So I can also give something back to the community.

**Comment by ashnazg** [comment]
@schengawegga since this package is marked as working with PHP 5.0.0, do you know for sure these changes also work on PHP5?

**Review by ashnazg — APPROVED** [review]

**Comment by ashnazg** [comment]
I pulled the branch and got a good-as-normal Travis build, so I'm convinced.

**Pull request merged**
