### PR TITLE
added php72

### PR DESCRIPTION
**Pull request by kokspflanze**
added php71 and php72 in travis.yml
fixed countable warnings

### CODE REVIEW

**Comment by hypermkt** [comment]
LGTM! ( I am not a maintainer of PEAR so I can't merge but LGTM ) I hope to review and merge somebody.

**Comment by hypermkt** [comment]
@till @cweiske 
It's not my PR but I also hope to add PHP 7.1 and 7.2 to travis. so Could you review this PR?

**Comment by hypermkt** [comment]
@convissor @LawnGnome 
It's not my PR but I also hope to add PHP 7.1 and 7.2 to travis. so Could you review this PR?

**Comment by till** [comment]
PR LGTM also. Not entirely sure why Travis-CI didn't run. Does it need to be enabled for this repo?

**Comment by till** [comment]
@kokspflanze Can you add a commit? I think I enabled the repository on Travis-CI.

**Comment by kokspflanze** [comment]
@till added =)

**Comment by kokspflanze** [comment]
thats why 5.3 fail=(
```
PHP 5.3 is supported only on Precise.
See https://docs.travis-ci.com/user/reference/trusty#PHP-images on how to test PHP 5.3 on Precise.
Terminating.
```

**Comment by till** [comment]
@ashnazg @cweiske Can we do a PEAR-DB-2.0.0 release with these additions to show that we no longer support PHP 5.3? (Had this in my notifications for too long.)

**Comment by ashnazg** [comment]
@till I'll try to look at it this week.

**Comment by kokspflanze** [comment]
for php5.3 i added a matrix entry to use `precise` as dist

**Review by ashnazg — APPROVED** [review]

**Comment by mpdude** [comment]
@ashnazg Could you be so kind to tag a Composer package release for this? 

Not sure if it's BC, but a 2.0 release would be fine for me as well.

Thanks!

**Comment by mpdude** [comment]
@ashnazg and @cweiske

A new release with these changes would really be helpful, as Composer does not pull in transitive `dev` dependencies unless you relax preferred stability constraints.

In other words, you cannot get rid of warnings on PHP 7.2 if pear/db is a transitive dependency.

I am not sure about the PEAR release process and maintainership: Can you release/tag a new version here if it does not at the same time show up in pear.php.net?

If you really care about leaving PHP 5.3 as a supported platform behind, tag 1.10.0 - you could then still release critical bug fixes for PHP 5.3 as 1.9.x.

No need for a 2.0 release IMO, no breaking changes here.

**Comment by ashnazg** [comment]
@mpdude released as v1.9.3.

**Pull request merged**
